# Generated by Django 4.2.11 on 2026-05-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS content;',
            reverse_sql='DROP SCHEMA IF EXISTS content CASCADE;'
        )
    ]
